## Basic operations
## Tensor types
## Importing data
## Lazy loading

In [1]:
import tensorflow as tf

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b)

with tf.Session() as sess:
    print(sess.run(x))

5


### Visuallize with TensorBoard

In [2]:
import tensorflow as tf

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b)

# 
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))
    
writer.close()

5


### Explicitly name variables

In [3]:
import tensorflow as tf

a = tf.constant(2, name = 'a')
b = tf.constant(3, name = 'b')
x = tf.add(a,b, name = 'add')

# 
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))
    
writer.close()

5


## Constants, Sequences, Variables, Ops

In [6]:
# Define constants matrix
# Multiplication

a = tf.constant([2,2], name = 'a')
b = tf.constant([[0,1], [2,3]], name = 'b')
x = tf.multiply(a,b,name = 'mul')

print(b.shape)
with tf.Session() as sess:
    print(sess.run(x))

(2, 2)
[[0 2]
 [4 6]]


### Tensors filled with a specific value

In [6]:
# Tensors filled with a specific value
shape = [2,3]
tf.zeros(shape, dtype = tf.float32, name = None)

<tf.Tensor 'zeros:0' shape=(2, 3) dtype=float32>

In [8]:
# create tensor of shape and type as the input_tensor but all elements are zeros
input_tensor = tf.constant([[0,1], [2,3], [4,5]])
tf.zeros_like(input_tensor)

<tf.Tensor 'zeros_like:0' shape=(3, 2) dtype=int32>

In [9]:
dims = [2,3]
value = 8
tf.fill(dims, value, name = None)

<tf.Tensor 'Fill:0' shape=(2, 3) dtype=int32>

### Constants as sequences

In [10]:
start = 10.0
stop = 13.0
num = 4
tf.lin_space(start, stop, num, name = None)

<tf.Tensor 'LinSpace:0' shape=(4,) dtype=float32>

In [11]:
start = 3
limit = 18
delta = 3
tf.range(start, limit, delta, dtype = None, name = 'range')

<tf.Tensor 'range:0' shape=(5,) dtype=int32>

### Randomly generated constants

tf.set_random_seed(seed)
tf.random_normal([2,3])
tf.truncated_normal([2,3])

In [14]:
tf.set_random_seed(42)
tf.random_normal([2,3])

<tf.Tensor 'random_normal_1:0' shape=(2, 3) dtype=float32>

### Divide

In [15]:
a = tf.constant([2,2], name = 'a')
b = tf.constant([[0,1],[2,3]], name = 'b')
with tf.Session() as sess:
    print(sess.run(tf.div(b,a)))
    print(sess.run(tf.divide(b,a)))
    print(sess.run(tf.floordiv(b,a)))

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
[[0 0]
 [1 1]]
[[0.  0.5]
 [1.  1.5]]
[[0 0]
 [1 1]]


### TF vs NP Data Type

In [17]:
import numpy as np
sess = tf.Session()
a = tf.zeros([2,3], dtype = np.float32)
print(type(a))
a_out = sess.run(a)
print(type(a))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


## Variables

1. ```tf.Variable``` is a class with many ops

```
x = tf.Variable(...)

x.initializer  # init op
x.value()      # read op
x.assign(...)     # write op

```

In [19]:

s = tf.Variable(2, name = 'scalar')
m = tf.Variable([[0,1],[2,3]], name = 'matrix')
W = tf.Variable(tf.zeros([784,10]))

s = tf.get_variable('scalar', initializer = tf.constant(2))
m = tf.get_variable('matrix', initializer = tf.constant([[0,1], [2,3]]))
W = tf.get_variable('big_matirx', shape = (784,10), initializer = tf.zeros_initializer())

### Variable initializer
1. initialize all variables at once
2. initialize a subset of variables
3. initialize single variable

In [23]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

In [26]:
with tf.Session() as sess:
    sess.run(tf.variables_initializer([W,m]))
    print(W)
    print(W.eval())

<tf.Variable 'big_matirx:0' shape=(784, 10) dtype=float32_ref>
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [27]:
W = tf.Variable(tf.truncated_normal([700,10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

[[ 0.20503671  0.1157805   0.8499046  ...  0.11996338  0.6808388
  -1.4422369 ]
 [ 0.7095585  -0.3555831  -1.2575859  ...  1.8628057  -0.87443256
  -0.18835253]
 [ 0.75591874 -1.2778344   0.6438342  ... -1.2059604  -1.9878682
  -0.3099065 ]
 ...
 [-0.9589257  -0.20681153  0.88503534 ...  0.3831197  -1.3271812
  -0.7059688 ]
 [ 1.7268467   0.7580851   0.16860734 ...  0.14078079  0.7255882
  -0.0672735 ]
 [-0.6703583   1.5578401  -0.6143904  ... -1.1511478  -0.37463826
  -1.367281  ]]


### ```tf.assign(...)```

In [28]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

10


```W.assign(100)``` created an assign operation
That op needs to be executed in a session to take effect

In [29]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(assign_op)
    print(W.eval())

100


In [32]:
my_var = tf.Variable(2)

# assign a * 2 to a and call that op a_times_two
my_var_times_two = my_var.assign(my_var * 2)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    sess.run(my_var_times_two)
    print(my_var.eval())
    sess.run(my_var_times_two)
    print(my_var.eval())
    sess.run(my_var_times_two)
    print(my_var.eval())

4
8
16


### Each session maintain its own copy of variables

In [35]:
W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(8)))
print(sess2.run(W.assign_sub(2)))

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(50)))

sess1.close()
sess2.close()

18
8
28
-42


## Placeholders
``` tf.placeholder(dtype, shape = None, name = None) ```

In [40]:
# create a placeholder with 3 elements
a = tf.placeholder(tf.float32, shape = [3])
b = tf.constant([5,5,5], tf.float32)
c = tf.add(a,b)
with tf.Session() as sess:
    print(sess.run(c, feed_dict = {a: [1,2,3]}))

[6. 7. 8.]
